import Head from "next/head";
import Hero from "@/components/Hero/hero";
import About from "@/components/About/about";
import Benefit from "@/components/Benefit/benefit";
import Collection from "@/components/Collection/collection";
import Collaboration from "@/components/Collaboration/collaboration";
import Team from "@/components/Team/team";
import Articles from "@/components/Articles/articles";
import NewsLetter from "@/components/NewsLetter/newsLetter";
import Footer from "@/components/Footer/footer";
import FAQ from "@/components/FAQ/faq";
import Journey from "@/components/Journey/journey";

export default function Home() {

  return (
    <>
      <Head>
        <title>NFTVERSE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <About />
      <Benefit />
      <Collection />
      <Collaboration />
      <Journey />
      <Team />
      <FAQ />
      <Articles />
      <NewsLetter />
      <Footer />
    </>
  );
}
